### ISSUE TITLE
 subscript out of bounds error

### ISSUE THREAD

**Issue by mingsnu** [earthlab/smapr#33]
Hi, I get the following error message.
Do you know what is the possible reason?
Thank you!
```
> available_data <- find_smap(id = "SPL3SMP", date = "2017-01-01", version = 4)
Error in rvest::html_table(nodes)[[1]] : subscript out of bounds
```

**Comment by mbjoseph** [comment]
Thanks - nothing is jumping out to me from that, but how about the output from the following: 

```r
library(smapr)
available_data <- find_smap(id = "SPL3SMP", date = "2017-01-01", version = 4)
sessionInfo()
```

My guess is maybe this is an rvest version issue? I am using rvest_0.3.2 locally.

**Comment by mbjoseph** [comment]
I'm going to close this issue - if you're still having problems, you could use the smapr Docker environment: https://hub.docker.com/r/earthlab/smapr/
