### ISSUE TITLE
Add visualization of typical workflow to README

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/smapr#38]
@marcosci points to a neat example here: https://github.com/socialcopsdev/rLandsat in https://github.com/ropensci/onboarding/issues/231

For smapr this is: 

`find_smap` ==> `download_smap` ==> `list_smap` ==> `extract_smap`

I wonder whether there's a way to programmatically do this without needing to create a figure in a vector graphics editor...

**Comment by marcosci** [comment]
Tikz? :-P

Or just make a network, name the nodes accordingly and plot it?

**Comment by mbjoseph** [comment]
Opted for a simpler solution - text! https://github.com/earthlab/smapr/commit/d0e2285f4079e7e5013827d0fc352a1064a6287f#diff-5140cd39fa2897e01ffbfb8db0999940R126
